### ISSUE TITLE
Validate sdflogin nodes are correct

### ISSUE THREAD

**Issue by mmccul** [slaclab/sdf-docs#41]
I see the old sdflogin hostnames are listed, not the new ones which use two zeros (e.g. sdflogin003).  Can you confirm the targets in the documentation at https://github.com/slaclab/sdf-docs/blob/master/accounts-and-access.md ?

**Comment by pjpascual** [comment]
The new hostnames (sdflogin00*) are for the S3DF cluster, sdf-login* are for the older SDF cluster. The S3DF documentation can be found in the `s3df` branch, although it currently doesn't list the new bastion hosts by name.
